### ISSUE TITLE
Issues and Fixes when Building

### ISSUE THREAD

**Issue by paul0noah** [LPMP/BDD#13]
I recently wanted to build BDD solver python-bindings on my machine (Linux Ubuntu 22.04, Core i9 12900k, RTX3060) via 
```
git clone https://github.com/LPMP/BDD
cd BDD
git submodule update --remote --recursive --init
python setup.py install # where python command refers to python 3 installation 
```

and encountered several issues. As a reference (and maybe for future fixes) i post them here so not everyone has to go on the journey to solve them :)

My compiler(s) are complaining about multiple things:
- `size_t` not found. Fix: add `#include <stddef.h>` to this line of [two_dimensional_variable_array.hxx](https://github.com/LPMP/BDD/blob/4cac38318e07ae97049ada1bb95bbd7893afeec1/include/two_dimensional_variable_array.hxx#L7)
- "narrowing conversion" in [incremental_mm_agreement_rounding_cuda.cu](https://github.com/LPMP/BDD/blob/4cac38318e07ae97049ada1bb95bbd7893afeec1/src/incremental_mm_agreement_rounding_cuda.cu#L309). (Definitely just a temporary) fix: replace the linked line with `thrust::transform(first, last, delta_it_begin, mm_types_transform<typename SOLVER::value_type>{(float)cur_delta, (float)max_incon_mm_diff, 2.0, false});` (basically casting `cur_delta` and `max_incon_mm_diff` ALWAYS to float which might cause precision loss when using `double`-solvers)
- `file <cub/detail/detect_cuda_runtime.cuh not found`. fix: 1) navigate with console to `<bdd_root>/external/thrust/dependencies/cub/` and `git checkout main && git pull` (in fact, before building the bdd project i did perform `git submodule update --init --recursive --remote`  which should actually solve it but it didnt...) 
- `file <cuda_runtime.h> not found`. Fix: i added after [this](https://github.com/LPMP/BDD/blob/4cac38318e07ae97049ada1bb95bbd7893afeec1/CMakeLists.txt#L11) line `include_directories("${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")`

**Comment by aabbas90** [comment]
Thanks for suggesting the changes! All issues are now resolved (at-least on my side).
